### ISSUE TITLE
Add Test Case for English.

### ISSUE THREAD

**Issue by torounit** [visualive/va-excerpt-from-content#6]

**Comment by torounit** [comment]
need english test.

and people that Japanese do not know , to be able to contribution!

**Comment by kuck1u** [comment]
Create a class that inherits the VisuAlive_ExcerptFromContentTest and changed the sentence in English.

**Comment by kuck1u** [comment]
Create a class that inherits the VisuAlive_ExcerptFromContentTest and changed the sentence in English.
